# Site settings
title: Sanjana Nayar
description: Hey guys! Welcome to my personal website. I post my experiences and interests here.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sanjana Nayar
user_description: I'm Sanjana Nayar and I'm from Kerala, India, pursuing my Bachelor's in Computer Science from Amrita University. I enjoy reading, travelling, trying new things and ofcourse, coding!
user_title: Aspiring Software Developer
email: sanjananayar2k1@gmail.com
twitter_username: Sanjana24545213
github_username:  sanjana091001

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
